name: Deploy Spring Boot App to OCI Kubernetes

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'openjdk'
          java-version: '23'
          cache: 'maven'

      - name: Build Spring Boot Application
        run: mvn clean package

      - name: Log in to Oracle Cloud Container Registry (OCIR)
        run: echo "${{ secrets.OCI_AUTH_TOKEN }}" | docker login $OCI_REGION.ocir.io -u "${{ secrets.OCI_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t $OCI_REGION.ocir.io/$IMAGE_NAME:latest .
          docker push $OCI_REGION.ocir.io/$IMAGE_NAME:latest

      - name: Configure Kubernetes
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s-deployment.yml
          kubectl rollout status deployment/$DEPLOYMENT_NAME
